image: 'rust:1'

stages:
    - lint
    - build
    - test

variables:
    CARGO_HOME: $CI_PROJECT_DIR/cargo
    APT_CACHE_DIR: $CI_PROJECT_DIR/apt
    GIT_SUBMODULE_STRATEGY: recursive

before_script:
    - apt-get update -yq
    - apt-get install -o dir::cache::archives="$APT_CACHE_DIR" -y

lint:
    stage: lint
    script:
        - rustup component add rustfmt
        - rustup component add clippy
        - cargo fmt -- --check
        - cargo clippy

build:
    stage: build
    script:
        - cargo build

test:

    stage: test

    variables:
        ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092,INTERNAL://localhost:9093'
        LISTENERS: 'PLAINTEXT://0.0.0.0:9092,INTERNAL://0.0.0.0:9093'
        SECURITY_PROTOCOL_MAP: 'PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT'
        INTER_BROKER: 'INTERNAL'
        PHAEDRA_INGEST_CONFIG: 'ci_config.toml'

    services:
        - name: krisgeus/docker-kafka
          alias: kafka

    script:
        # unit tests
        - cargo test --lib
        # integration tests
        - cargo test --test server

cache:
    paths:
        - apt/
        - cargo/
        - target/
