[package]
name = "ingest"
version = "0.1.0"
authors = ["Robert Ignat <robert.ignat91@gmail.com>"]
edition = "2018"

[dependencies]
futures = "0.3.5"
rdkafka = "0.24.0"
bytes = "0.5.6"
json = "0.12.4"
actix = "0.10.0"
actix-rt = "1.1.1"
actix-http = "2.0.0"
actix-web = "3.0.2"
actix-web-actors = "3.0.0"
tracing = "0.1.19"
tracing-futures = "0.2.4"
serde = { version = "1.0.116", features = ["derive"] }

[dependencies.tokio]
version = "0.2.22"
features = ["signal", "sync"]

[dependencies.common]
path = "vendor/common"
features = ["actix_web"]

[dev-dependencies]
url = "2.1.1"
reqwest = "0.10.8"
tokio-tungstenite = "0.11.0"
