[package]
name = "ingest"
version = "0.2.0"
edition = "2021"

[dependencies]
futures = "0.3.26"
bytes = "1.3.0"
json = "0.12.4"
#actix = "0.10.0"
#actix-rt = "1.1.1"
#actix-http = "2.0.0"
actix-web = "4.3.0"
#actix-web-actors = "3.0.0"
tracing = "0.1.19"
tracing-futures = "0.2.4"

[dependencies.serde]
version = "1.0.116"
features = ["derive"]

[dependencies.tokio]
version = "1.25.0"
features = ["full"]

[dependencies.tokio-stream]
version = "0.1.11"
features = ["signal"]

[dependencies.rdkafka]
version = "0.29.0"
features = ["ssl", "tracing"]

[dependencies.common]
path = "vendor/common"
features = ["actix_web"]

[dev-dependencies]
reqwest = "0.11.14"
