[package]
name = "ingest"
version = "0.1.0"
authors = ["Robert Ignat <robert.ignat91@gmail.com>"]
edition = "2018"

[dependencies]
futures = "0.3.4"
rdkafka = "0.23.1"
bytes = "0.5.4"
json = "0.12.1"
actix = "0.9.0"
actix-rt = "1.0.0"
actix-http = "1.0.1"
actix-web = "2.0.0"
actix-web-actors = "2.0.0"
uuid = { version = "0.8.1", features = ["v4"] }
tracing = "0.1.13"
tracing-subscriber = "0.2.3"
tracing-futures = "0.2.3"
serde = { version = "1.0.104", features = ["derive"] }
toml = "0.5.6"

[dependencies.tokio]
version = "0.2.13"
features = ["signal", "sync"]

[dependencies.common]
path = "vendor/common"
features = ["actix_web"]

[dev-dependencies]
url = "2.1.1"
reqwest = "0.10.4"
tokio-tungstenite = "0.10.1"
