# local address to bind the service to
addr = '127.0.0.1:8088'
# prefix used for tenant topics
destination_topic = 'events'

[headers]
# configure kafka header names
schema_id = "ncube-ingest-schema-id"
ip = "ncube-ingest-ip"

[logging]
# output logs in JSON format
fmt_json = false

[librdkafka_config]
# accepts any librdkafka configuration value
"bootstrap.servers" = "localhost:9093"
