[service]
# local address to bind the service to
addr = '127.0.0.1:8088'

[headers]
# configure kafka header names
schema_id = "ncube-ingest-schema-id"
ip = "ncube-ingest-ip"

[logging]
fmt_json = false
console = true
otel_tracing = true
otel_metrics = true

[[librdkafka]]
name = "main"
[librdkafka.config]
# accepts any librdkafka configuration value
"bootstrap.servers" = "localhost:9093"
[librdkafka.secrets]
# the sasl.password secret is read from a file
sasl_password_path = "/path/to/sasl_password"

[[librdkafka]]
name = "other"
[librdkafka.config]
"bootstrap.servers" = "localhost:9094"

[service.default_schema_config]
destination_topic = 'events'
content_type = "application/jsonlines"
forward_request_url = false
forward_request_http_headers = false
response_status = 200
allowed_methods = ["POST"]


[[service.schema_config]]
schema_id = "key"
content_type = "application/json"
forward_request_url = true
forward_request_http_headers = true
response_status = 200
python_module_search_path = "src"
librdkafka_config = "other"

[[service.schema_config.python_request_processor]]
methods = ["GET", "POST"]
processor = "webhook.service_x:ServiceXProcessor"
implements_process_head = true
process_is_blocking = true
process_head_is_blocking = false
