version: "3.7"

networks:
    dev_net:
        driver: bridge

volumes:
    kafka:
    zookeeper:
    zookeeper-log:


services:
    zookeeper-server:
        image: zookeeper

        restart: on-failure

        networks:
            - dev_net

        volumes:
            - zookeeper:/data
            - zookeeper-log:/datalog

    kafka-server:
        image: bitnami/kafka

        restart: on-failure

        depends_on:
            - zookeeper-server

        networks:
            - dev_net

        volumes:
            - kafka:/bitnami/kafka

        ports:
            - "19092:19092/tcp"

        environment:
            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-server:2181
            - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:19092
            - KAFKA_CFG_LISTENERS=PLAINTEXT://:19092
            - ALLOW_PLAINTEXT_LISTENER=yes
