### send json
POST {{host}}/key
Content-Type: application/json

{}

### send bogus
POST {{host}}/key
Content-Type: application/json

< ./nonutf8

### send jsonlines
POST {{host}}/key
Content-Type: application/jsonlines

{"id": 10, "value": "content"}
{"id": 11, "value": "content"}
{"id": 12, "value": "content"}
{"id": 10, "value": "content"}
{"id": 11, "value": "content"}
{"id": 12, "value": "content"}
{"id": 10, "value": "content"}
{"id": 11, "value": "content"}
{"id": 12, "value": "content"}